### PR TITLE
Fix TBC swaps

### LINKED ISSUE #1024: [Bug]: Swap with XYK and TBC pool don't work
### Preconditions

- Setup XYK and TBC pool for TBCD with the same price

### Steps to reproduce

- Perform swap TBCD-XOR without filters

### Actual behavior

Swap fails with `poolXYK.CalculatedValueIsOutOfDesiredBounds`

### Expected behavior

Swap successfull

### Environment

{"label"=>"Production"}

### Operating System

_No response_

### Additional context

Swap should split to 2 parts by smart split to reproduce this bug. In this case buyback performed by TBC pool changes price of TBCD and second part of the swap (which is usually XYK pool) fails with slippage error

### PR DESCRIPTION
**Pull request by vovac12**
Fixes #1024

### CODE REVIEW

File: pallets/multicollateral-bonding-curve-pool/src/mock.rs [hunk 1]
```diff
@@ -1035,3 +1036,12 @@ impl ExtBuilder {
...
 }
+
+pub fn run_to_block(n: u64) {
+    while System::block_number() < n {
+        System::on_finalize(System::block_number());
+        System::set_block_number(System::block_number() + 1);
+        System::on_initialize(System::block_number());
+        Mcbcp::on_initialize(System::block_number());
+    }
+}
```
Comment (wer1st) [inline pallets/multicollateral-bonding-curve-pool/src/mock.rs:1047]: Why in mock file?
Looks like it's better to move in tests

File: pallets/multicollateral-bonding-curve-pool/src/lib.rs [hunk 2]
```diff
@@ -412,8 +414,13 @@ pub mod pallet {
...
     #[pallet::getter(fn pending_free_reserves)]
-    pub type PendingFreeReserves<T: Config> =
-        StorageValue<_, Vec<(AssetIdOf<T>, Balance)>, ValueQuery>;
+    pub type PendingFreeReserves<T: Config> = StorageMap<
+        _,
+        Blake2_128Concat,
+        BlockNumberFor<T>,
+        BTreeMap<AssetIdOf<T>, Balance>,
+        ValueQuery,
+    >;
```
Comment (wer1st) [inline pallets/multicollateral-bonding-curve-pool/src/lib.rs:423]: Do we need a migration for that?

Comment (wer1st) [reply pallets/multicollateral-bonding-curve-pool/src/lib.rs:423]: And update the `STORAGE_VERSION`?

Comment (vovac12) [reply pallets/multicollateral-bonding-curve-pool/src/lib.rs:423]: Done

**Review by wer1st — APPROVED** [review]

File: pallets/multicollateral-bonding-curve-pool/Cargo.toml [hunk 3]
```diff
@@ -27,6 +27,7 @@ serde = { version = "1.0.101", default-features = false, optional = true, featur
 sp-arithmetic = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
 sp-runtime = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
 sp-std = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
+sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/Cargo.toml:30]:
```suggestion
```
No need in this dep, it is used to construct AssetId in bench. But there is more convenient way to do it.

File: pallets/multicollateral-bonding-curve-pool/Cargo.toml [hunk 4]
```diff
@@ -68,6 +69,7 @@ std = [
     'sp-arithmetic/std',
     'sp-runtime/std',
     'sp-std/std',
+    'sp-core/std',
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/Cargo.toml:72]:
```suggestion
```

File: pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs [hunk 5]
```diff
@@ -93,59 +91,69 @@ fn setup_benchmark<T: Config>() -> Result<(), &'static str> {
...
-        &owner.clone(),
-        balance!(50000000),
+    T::AssetManager::mint_to(&XOR.into(), &owner.clone(), &owner.clone(), balance!(3000)).unwrap();
+    register_tbc_for_asset::<T>(DAI.into());
+    register_tbc_for_asset::<T>(VAL.into());
+    Ok(())
+}
+
+fn gen_asset_id<T: Config>(n: u32) -> AssetIdOf<T> {
+    let asset_id = sp_core::H256::from_low_u64_le(n as u64).into();
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs:101]:
```suggestion
    let asset_id = T::AssetManager::gen_asset_id_from_any(&("mbc_bench", n));
```

File: pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs [hunk 6]
```diff
@@ -93,59 +91,69 @@ fn setup_benchmark<T: Config>() -> Result<(), &'static str> {
         permissions::Scope::Unlimited,
     )
     .unwrap();
-    T::AssetManager::mint_to(&XOR.into(), &owner.clone(), &owner.clone(), balance!(5000)).unwrap();
-    T::AssetManager::mint_to(
-        &DAI.into(),
-        &owner.clone(),
-        &owner.clone(),
-        balance!(50000000),
+    T::AssetManager::mint_to(&XOR.into(), &owner.clone(), &owner.clone(), balance!(3000)).unwrap();
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs:94]:
```suggestion
    T::AssetManager::mint_to(&XOR.into(), &owner, &owner, balance!(3000)).unwrap();
```

File: pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs [hunk 7]
```diff
@@ -93,59 +91,69 @@ fn setup_benchmark<T: Config>() -> Result<(), &'static str> {
...
+    let owner = alice::<T>();
+    let owner_origin: <T as frame_system::Config>::RuntimeOrigin =
+        RawOrigin::Signed(owner.clone()).into();
+
+    T::AssetManager::mint_to(&XOR.into(), &owner.clone(), &owner.clone(), balance!(1000)).unwrap();
     T::AssetManager::mint_to(
-        &VAL.into(),
+        &asset_id,
         &owner.clone(),
         &owner.clone(),
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs:129]:
```suggestion
        &owner,
        &owner,
```

File: pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs [hunk 8]
```diff
@@ -93,59 +91,69 @@ fn setup_benchmark<T: Config>() -> Result<(), &'static str> {
...
+        .unwrap();
+    asset_id
+}
+
+fn register_tbc_for_asset<T: Config>(asset_id: AssetIdOf<T>) {
+    let owner = alice::<T>();
+    let owner_origin: <T as frame_system::Config>::RuntimeOrigin =
+        RawOrigin::Signed(owner.clone()).into();
+
+    T::AssetManager::mint_to(&XOR.into(), &owner.clone(), &owner.clone(), balance!(1000)).unwrap();
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs:125]:
```suggestion
    T::AssetManager::mint_to(&XOR.into(), &owner, &owner, balance!(1000)).unwrap();
```

File: pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs [hunk 9]
```diff
@@ -93,59 +91,69 @@ fn setup_benchmark<T: Config>() -> Result<(), &'static str> {
...
     .unwrap();
 
-    XYKPool::<T>::initialize_pool(owner_origin.clone(), DEX.into(), XOR.into(), DAI.into())
-        .unwrap();
-    XYKPool::<T>::initialize_pool(owner_origin.clone(), DEX.into(), XOR.into(), VAL.into())
-        .unwrap();
+    XYKPool::<T>::initialize_pool(owner_origin.clone(), DEX.into(), XOR.into(), asset_id).unwrap();
 
     XYKPool::<T>::deposit_liquidity(
         owner_origin.clone(),
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/benchmarking.rs:137]:
```suggestion
        owner_origin,
```

File: pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs [hunk 10]
```diff
@@ -0,0 +1,103 @@
...
+            return <T as frame_system::Config>::DbWeight::get().reads(1);
+        }
+        info!("Applying migration to version 4: Move free reserves distribution to Hooks");
+        let pending_free_reserves = old_storage::PendingFreeReserves::<T>::take()
+            .into_iter()
+            .collect::<BTreeMap<AssetIdOf<T>, Balance>>();
+        if !pending_free_reserves.is_empty() {
+            info!("Migrate pending free reserves: {:?}", pending_free_reserves);
+            crate::PendingFreeReserves::<T>::insert(
+                frame_system::Pallet::<T>::block_number() + One::one(),
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs:43]:
```suggestion
                frame_system::Pallet::<T>::block_number() + T::BlockNumber::one(),
```
Bit more explanatory.

File: pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs [hunk 11]
```diff
@@ -0,0 +1,103 @@
...
+                pending_free_reserves,
+            );
+        } else {
+            info!("No pending free reserves to migrate");
+        }
+        StorageVersion::new(4).put::<Pallet<T>>();
+        <T as frame_system::Config>::BlockWeights::get().max_block
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs:50]: I wonder, why we return this value instead of counting actual one?

File: pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs [hunk 12]
```diff
@@ -0,0 +1,103 @@
...
+            "must upgrade linearly"
+        );
+        Ok(state)
+    }
+
+    #[cfg(feature = "try-runtime")]
+    fn post_upgrade(state: Vec<u8>) -> Result<(), &'static str> {
+        ensure!(
+            !old_storage::PendingFreeReserves::<T>::exists(),
+            "Old storage value stil presented"
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs:67]:
```suggestion
            "Old storage value still present"
```

File: pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs [hunk 13]
```diff
@@ -0,0 +1,103 @@
...
+        } else {
+            ensure!(
+                crate::PendingFreeReserves::<T>::iter().count() == 1,
+                "Pending free reserves have more than one entry"
+            );
+            let (block_number, value) = crate::PendingFreeReserves::<T>::iter()
+                .next()
+                .ok_or("Empty pending free reserves")?;
+            ensure!(
+                block_number == frame_system::Pallet::<T>::block_number() + One::one(),
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs:85]:
```suggestion
                block_number == frame_system::Pallet::<T>::block_number() + T::BlockNumber::one(),
```

File: pallets/multicollateral-bonding-curve-pool/src/tests.rs [hunk 14]
```diff
@@ -3354,12 +3396,12 @@ mod tests {
...
 
             // val is not enough for one of distributions, it's still present
-            MBCPool::on_initialize(RETRY_DISTRIBUTION_FREQUENCY.into());
+            run_to_block(RETRY_DISTRIBUTION_FREQUENCY as u64 * 3);
             let free_reserves_balance_4 =
                 Assets::free_balance(&USDT, &MBCPool::free_reserves_account_id().unwrap()).unwrap();
             assert_eq!(
-                MBCPool::pending_free_reserves(),
-                vec![(USDT, second_pending_balance)]
+                MBCPool::pending_free_reserves(RETRY_DISTRIBUTION_FREQUENCY as u64 * 3 + 2),
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/tests.rs:3403]: I think it is better to change type of `RETRY_DISTRIBUTION_FREQUENCY` to `u64`.

File: pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs [hunk 15]
```diff
@@ -0,0 +1,103 @@
+use crate::Config;
```
Comment (Alexey-N-Chernyshov) [inline pallets/multicollateral-bonding-curve-pool/src/migrations/v4.rs:1]: Please, don't forget to add migration to `runtime/src/migration`.

**Review by Alexey-N-Chernyshov — COMMENTED** [review]
Most of comments related to clippy since it is disabled for the crate.

File: pallets/multicollateral-bonding-curve-pool/src/tests.rs (hunk 14 above)
Comment (vovac12) [reply pallets/multicollateral-bonding-curve-pool/src/tests.rs]: Added constant to Config trait

**Review by Alexey-N-Chernyshov — APPROVED** [review]
